name: S.C.P - Java Edition (para dispositivos Windows e Linux)

on:
  workflow_dispatch:
    inputs:
      build-version:
        description: "Versão do Jogo"
        required: true
        default: "1.00.00"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cheque de Repositório
        uses: actions/checkout@v4
      - name: Configuração do Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "22"
      - name: Definição de Variáveis de Ambiente
        run: |
         echo 'BUILD_VERSION=${{ inputs.build-version }}' >> $GITHUB_ENV
         echo 'JAR_FILE_NAME=scp-java-edition-${{ inputs.build-version }}.jar' >> $GITHUB_ENV
      - name: Compilação do Código e Montagem do JAR
        run: |
         mkdir -p bin
         javac -d bin source/org/scp/Main.java
         mkdir -p dist
         jar cfe dist/${{ env.JAR_FILE_NAME }} Main -C bin .
      - name: Publicação de Artefato
        uses: actions/upload-artifact@v4
        with:
          name: scp-java-edition-build
          path: dist/${{ env.JAR_FILE_NAME }}
